language: go
go:
  - 1.6
env:
  - secure: "tfC9EHTTt1qsowjixcq/zEqHf76ex4fp3MlejRMqwgETrSlzFV62p0bbQbWJvzBbIFZ1H+0jUtqVzb8kxOlDaTRygWsYWEF9wyJj/ahIj/C18QGOUjlj6j3MJ8XukIuy0cJwO2iMQLsy2CT6IojAx7DVIXc3mA/9e3E+qkYZFubSeaU0h9p9Wz5YNMI4uJXll6mBHWZwIYLyYgqZJxmkqtWlm9PEx2n7FabS9ZiH9OLMruoErDU7b4wJNaC4hWJ5uBY2FbZWI3YSclZ/a+Ml9XtG6eCMqc+PrKhk0iHNJmyBvYbJLLhg1TdJl8MBLcvjVRb5gN4JkSDf/Xp1Rx1EVKZ3xJwipV759wGpAJxRAHQUk8IPVlfhJOjI1yId3TwIUHEpwx+686fvcwteiZSXLoO+JXtEy6Izs4tCx9UekYgFBfm3jZTXpgGaKuxygjH5/mdX/hTCbPH9tJMM3VdYduvFttyhkYzqQnQ7WGvjdfh+HPE/pJzAtQw6v2QP/dQ0ALxXxClmTWXOfp7sKP2DGv8/ax/++DcpCOvjLAPlVXdqCjWR5fvYJDPOc+eu5V7F5RjTXdMaH97KJdDAVRkSPcdUu3WfZ3YrNaQWCQB6004a8k3UkTEwQKXJTVzuhE6njZ+5u0I7AxhBgr14YwP9/Q7/C97UZTye/FxFhaA2uRM="
services:
  - redis-server
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/garyburd/redigo/redis
  - rm -f main.go

script:
    - cd callp;REDIS_URL='redis://127.0.0.1:6379/0' go test -v -covermode=count -coverprofile=coverage.out -benchmem -bench .
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
